name: tw_queue
description: Queue up futures from multiple sources and await their return anywhere in your code.
version: 0.0.3
homepage: https://github.com/zeqinjie/tw_queue
repository: https://github.com/zeqinjie/tw_queue

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.16.3
  lints: ^2.0.1


