name: tw_queue
description: Queue up futures from multiple sources and await their return anywhere in your code.
version: 0.0.1
homepage: https://github.com/zeqinjie/tw_queue
repository: https://github.com/zeqinjie/tw_queue

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.3
  lints: ^2.0.1


